### ISSUE TITLE
ASIS GHOSH

### ISSUE THREAD

**Issue by asisjpg** [webshub/Shubha_Downloader#3]
ERROR MESSAGE:
Uncaught node.js Error 

TypeError: Cannot call method 'setValue' of undefined
    at null.<anonymous> (file:///C:/Program%20Files/Shubha%20Downloader/node_modules/shubhadownloader/save_settings.js:47:76)
    at EventEmitter.emit (events.js:96:17)
    at CsvReader._addRecord (C:\Program Files\Shubha Downloader\node_modules\ya-csv\lib\ya-csv.js:227:14)
    at CsvReader.parse (C:\Program Files\Shubha Downloader\node_modules\ya-csv\lib\ya-csv.js:160:26)
    at EventEmitter.emit (events.js:96:17)
    at ReadStream._emitData (fs.js:1363:29)
    at afterRead (fs.js:1347:10)
    at Object.wrapper [as oncomplete](fs.js:362:17)

More over: Initially only CSV data was downloaded from NCDEX; no AMIBROKER DATA was generated

**Comment by NAVAMANI** [comment]
I am also facing this same error every time i open shubha downloader .

Windows 8.

**Comment by webshub** [comment]
Hi,
If you are using Widows 7 or windows 8, this problem comes, Please "Run as admin". Please see video tutorial.
This known issue.

**Comment by asisjpg** [comment]
Ok--apparently this is not working--I will reinstall it later.

In my another Laptop, NCDEX data is downloaded--but it is not of normal 
Amibroker format--I tried to redefine it in another AXCII mode--but it 
failed. Could you guide ?

NCDEX EOD data need to be imported in Amibroker.

Thanks,

Asis

On 07/02/2013 07:42 AM, webshub wrote:

> Hi,
> If you are using Widows 7 or windows 8, this problem comes, Please 
> "Run as admin". Please see video tutorial.
> This known issue.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/webshub/Shubha_Downloader/issues/3#issuecomment-13217676. 

## 

Thanks & Regards,

Asis Ghosh
(Skype-id: asis.ghosh4)
